#!/usr/bin/env python3
"""
perception-items.json  ->  ~/Desktop/perception-items.xlsx

The JSON is the source of truth. This is a read-only view of it — edits in
Excel do not flow back. Re-run after changing the JSON.

    python3 export_perception_xlsx.py
    python3 export_perception_xlsx.py --out ~/somewhere/else.xlsx

Also recomputes `gap` and `ratio` in the JSON so the two files never disagree.
"""
import argparse, json, os, collections
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import DataBarRule

HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, 'perception-items.json')

FIELD_ORDER = ["id","kind","direction","ask","unit","perceived","actual","gap","ratio",
               "estimator","about","source","year","n","verified","note"]

HEAD = PatternFill('solid', fgColor='1F2430')
HF   = Font(color='FFFFFF', bold=True, size=10)
BORD = Border(bottom=Side(style='thin', color='DDDDDD'))
KIND = {'size':'DBEAFE','meta':'FCE7F3','trend':'FEF3C7','quiz':'DCFCE7','risk':'EDE9FE'}


def derive(items):
    """gap/ratio are meaningless on trend rows, where `actual` is a flag not a value."""
    for it in items:
        p, a = it.get('perceived'), it.get('actual')
        num = isinstance(p,(int,float)) and isinstance(a,(int,float))
        if it['kind'] == 'trend':
            it['gap'] = it['ratio'] = None
        else:
            it['gap']   = round(p-a, 1) if num else None
            it['ratio'] = round(p/a, 1) if num and a else None
    return items


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.expanduser('~/Desktop/perception-items.xlsx'))
    ap.add_argument('--no-writeback', action='store_true',
                    help="don't rewrite gap/ratio back into the JSON")
    a = ap.parse_args()

    raw = json.load(open(SRC), object_pairs_hook=collections.OrderedDict)
    items, sources = derive(raw['items']), raw['sources']

    if not a.no_writeback:
        raw['items'] = [collections.OrderedDict((f, it.get(f)) for f in FIELD_ORDER)
                        for it in items]
        json.dump(raw, open(SRC,'w'), indent=2, ensure_ascii=False)

    wb = Workbook()

    # ---------------- Items ----------------
    ws = wb.active; ws.title = 'Items'
    cols = [('id',26),('kind',9),('direction',10),('ask',70),('unit',16),
            ('perceived',11),('actual',10),('gap',9),('ratio',9),
            ('estimator',24),('about',26),('source',17),('year',7),('n',9),
            ('verified',9),('note',80),('url',52)]
    ws.append([c[0] for c in cols])
    for i,(name,w) in enumerate(cols,1):
        ws.column_dimensions[get_column_letter(i)].width = w
        c = ws.cell(1,i); c.fill = HEAD; c.font = HF
        c.alignment = Alignment(vertical='center')

    for it in items:
        ws.append([it.get(f) for f in FIELD_ORDER] +
                  [sources.get(it['source'],{}).get('url')])

    for r in range(2, ws.max_row+1):
        fill = PatternFill('solid', fgColor=KIND.get(ws.cell(r,2).value, 'FFFFFF'))
        for c in range(1, len(cols)+1):
            cell = ws.cell(r,c)
            cell.border = BORD
            cell.alignment = Alignment(vertical='top', wrap_text=(c in (4,16)))
            if c <= 3: cell.fill = fill
        ws.row_dimensions[r].height = 30

    ws.freeze_panes = 'B2'
    ws.auto_filter.ref = f"A1:{get_column_letter(len(cols))}{ws.max_row}"
    ws.conditional_formatting.add(f"H2:H{ws.max_row}",
        DataBarRule(start_type='num', start_value=-40, end_type='num',
                    end_value=40, color='F87171'))

    # ---------------- Sources ----------------
    s = wb.create_sheet('Sources')
    s.append(['key','items','cite','fielded','n','url'])
    for i,w in enumerate([18,7,66,46,40,58],1):
        s.column_dimensions[get_column_letter(i)].width = w
        c = s.cell(1,i); c.fill = HEAD; c.font = HF
    counts = collections.Counter(it['source'] for it in items)
    for k,v in sorted(sources.items(), key=lambda kv: -counts.get(kv[0],0)):
        s.append([k, counts.get(k,0), v.get('cite'), v.get('fielded'),
                  str(v.get('n')), v.get('url')])
    for r in range(2, s.max_row+1):
        for c in range(1,7):
            s.cell(r,c).alignment = Alignment(vertical='top', wrap_text=(c in (3,4,5)))

    # ---------------- Read me ----------------
    n = wb.create_sheet('Read me')
    n.column_dimensions['A'].width = 118
    for text, bold in [
        ('Perception items — export', True), ('', False),
        (f'{len(items)} items, {len(sources)} sources. Generated by export_perception_xlsx.py.', False),
        ('perception-items.json is the source of truth. Edits here do NOT flow back.', False), ('', False),
        ('KINDS', True),
        ('size   — how big is a group (perceived % vs true %)', False),
        ('meta   — what do others believe (perceived prevalence vs true prevalence)', False),
        ('trend  — which direction something is moving. actual = 0 means "it did not move that way".', False),
        ('         gap and ratio are blank on these rows on purpose.', False),
        ('quiz   — FIELDS ARE INVERTED. perceived = % who answered CORRECTLY,', False),
        ('         actual = 33.3, the score random guessing gives.', False),
        ('         A NEGATIVE gap is the damning one: worse than chance.', False), ('', False),
        ('DERIVED COLUMNS', True),
        ('gap    = perceived − actual', False),
        ('ratio  = perceived ÷ actual. How many times too big the estimate was.', False), ('', False),
        ('verified = the number was read off the primary source. Everything here is publishable.', False),
        ('Unverified leads live in the "queued" key of the JSON and are excluded from this file.', False),
    ]:
        n.append([text])
        cell = n.cell(n.max_row, 1)
        cell.font = Font(bold=bold, size=11 if bold else 10)
        cell.alignment = Alignment(wrap_text=True, vertical='top')

    wb.save(a.out)
    print(f"wrote {a.out}  ({len(items)} items, {round(os.path.getsize(a.out)/1024)} KB)")


if __name__ == '__main__':
    main()
