// Comprehensive Spanish vocabulary mapped to OpenMoji Unicode codepoints
// OpenMoji files are in images/openmoji/{CODEPOINT}.svg

const spanishVocab = {
    // ===== ANIMALS =====
    animals: [
        { spanish: "gato", english: "cat", code: "1F431" },
        { spanish: "perro", english: "dog", code: "1F436" },
        { spanish: "ratón", english: "mouse", code: "1F42D" },
        { spanish: "conejo", english: "rabbit", code: "1F430" },
        { spanish: "zorro", english: "fox", code: "1F98A" },
        { spanish: "oso", english: "bear", code: "1F43B" },
        { spanish: "panda", english: "panda", code: "1F43C" },
        { spanish: "koala", english: "koala", code: "1F428" },
        { spanish: "tigre", english: "tiger", code: "1F42F" },
        { spanish: "león", english: "lion", code: "1F981" },
        { spanish: "vaca", english: "cow", code: "1F404" },
        { spanish: "cerdo", english: "pig", code: "1F437" },
        { spanish: "caballo", english: "horse", code: "1F434" },
        { spanish: "burro", english: "donkey", code: "1FACF" },
        { spanish: "oveja", english: "sheep", code: "1F411" },
        { spanish: "cabra", english: "goat", code: "1F410" },
        { spanish: "camello", english: "camel", code: "1F42B" },
        { spanish: "llama", english: "llama", code: "1F999" },
        { spanish: "jirafa", english: "giraffe", code: "1F992" },
        { spanish: "elefante", english: "elephant", code: "1F418" },
        { spanish: "rinoceronte", english: "rhinoceros", code: "1F98F" },
        { spanish: "hipopótamo", english: "hippopotamus", code: "1F99B" },
        { spanish: "mono", english: "monkey", code: "1F435" },
        { spanish: "gorila", english: "gorilla", code: "1F98D" },
        { spanish: "pereza", english: "sloth", code: "1F9A5" },
        { spanish: "mapache", english: "raccoon", code: "1F99D" },
        { spanish: "canguro", english: "kangaroo", code: "1F998" },
        { spanish: "tejón", english: "badger", code: "1F9A1" },
        { spanish: "zorrillo", english: "skunk", code: "1F9A8" },
        { spanish: "castor", english: "beaver", code: "1F9AB" },
        { spanish: "nutria", english: "otter", code: "1F9A6" },
        { spanish: "murciélago", english: "bat", code: "1F987" },
        { spanish: "lobo", english: "wolf", code: "1F43A" },
        { spanish: "jabalí", english: "boar", code: "1F417" },
        { spanish: "ciervo", english: "deer", code: "1F98C" },
        { spanish: "bisonte", english: "bison", code: "1F9AC" },

        // Birds
        { spanish: "pájaro", english: "bird", code: "1F426" },
        { spanish: "águila", english: "eagle", code: "1F985" },
        { spanish: "pato", english: "duck", code: "1F986" },
        { spanish: "cisne", english: "swan", code: "1F9A2" },
        { spanish: "búho", english: "owl", code: "1F989" },
        { spanish: "flamenco", english: "flamingo", code: "1F9A9" },
        { spanish: "pavo", english: "turkey", code: "1F983" },
        { spanish: "gallo", english: "rooster", code: "1F413" },
        { spanish: "gallina", english: "chicken", code: "1F414" },
        { spanish: "pollito", english: "chick", code: "1F424" },
        { spanish: "pingüino", english: "penguin", code: "1F427" },
        { spanish: "paloma", english: "dove", code: "1F54A" },
        { spanish: "loro", english: "parrot", code: "1F99C" },
        { spanish: "pavo real", english: "peacock", code: "1F99A" },
        { spanish: "cuervo", english: "crow", code: "1F426-200D-2B1B" },
        { spanish: "ganso", english: "goose", code: "1FABF" },

        // Sea creatures
        { spanish: "pez", english: "fish", code: "1F41F" },
        { spanish: "delfín", english: "dolphin", code: "1F42C" },
        { spanish: "ballena", english: "whale", code: "1F40B" },
        { spanish: "tiburón", english: "shark", code: "1F988" },
        { spanish: "pulpo", english: "octopus", code: "1F419" },
        { spanish: "cangrejo", english: "crab", code: "1F980" },
        { spanish: "langosta", english: "lobster", code: "1F99E" },
        { spanish: "camarón", english: "shrimp", code: "1F990" },
        { spanish: "calamar", english: "squid", code: "1F991" },
        { spanish: "medusa", english: "jellyfish", code: "1FABC" },
        { spanish: "estrella de mar", english: "starfish", code: "1F seastar" },
        { spanish: "tortuga", english: "turtle", code: "1F422" },
        { spanish: "foca", english: "seal", code: "1F9AD" },
        { spanish: "coral", english: "coral", code: "1FAB8" },

        // Insects & small creatures
        { spanish: "mariposa", english: "butterfly", code: "1F98B" },
        { spanish: "abeja", english: "bee", code: "1F41D" },
        { spanish: "mariquita", english: "ladybug", code: "1F41E" },
        { spanish: "hormiga", english: "ant", code: "1F41C" },
        { spanish: "araña", english: "spider", code: "1F577" },
        { spanish: "oruga", english: "caterpillar", code: "1F41B" },
        { spanish: "caracol", english: "snail", code: "1F40C" },
        { spanish: "escarabajo", english: "beetle", code: "1FAB2" },
        { spanish: "grillo", english: "cricket", code: "1F997" },
        { spanish: "cucaracha", english: "cockroach", code: "1FAB3" },
        { spanish: "mosca", english: "fly", code: "1FAB0" },
        { spanish: "mosquito", english: "mosquito", code: "1F99F" },
        { spanish: "gusano", english: "worm", code: "1FAB1" },
        { spanish: "libélula", english: "dragonfly", code: "1F409" },

        // Reptiles & amphibians
        { spanish: "serpiente", english: "snake", code: "1F40D" },
        { spanish: "lagarto", english: "lizard", code: "1F98E" },
        { spanish: "cocodrilo", english: "crocodile", code: "1F40A" },
        { spanish: "rana", english: "frog", code: "1F438" },
        { spanish: "dinosaurio", english: "dinosaur", code: "1F996" },
        { spanish: "dragón", english: "dragon", code: "1F409" },
    ],

    // ===== FOOD & DRINK =====
    food: [
        // Fruits
        { spanish: "manzana", english: "apple", code: "1F34E" },
        { spanish: "pera", english: "pear", code: "1F350" },
        { spanish: "naranja", english: "orange", code: "1F34A" },
        { spanish: "limón", english: "lemon", code: "1F34B" },
        { spanish: "plátano", english: "banana", code: "1F34C" },
        { spanish: "sandía", english: "watermelon", code: "1F349" },
        { spanish: "uvas", english: "grapes", code: "1F347" },
        { spanish: "fresa", english: "strawberry", code: "1F353" },
        { spanish: "cereza", english: "cherry", code: "1F352" },
        { spanish: "melocotón", english: "peach", code: "1F351" },
        { spanish: "mango", english: "mango", code: "1F96D" },
        { spanish: "piña", english: "pineapple", code: "1F34D" },
        { spanish: "coco", english: "coconut", code: "1F965" },
        { spanish: "kiwi", english: "kiwi", code: "1F95D" },
        { spanish: "aguacate", english: "avocado", code: "1F951" },
        { spanish: "berenjena", english: "eggplant", code: "1F346" },
        { spanish: "arándano", english: "blueberry", code: "1FAD0" },
        { spanish: "aceituna", english: "olive", code: "1FAD2" },

        // Vegetables
        { spanish: "tomate", english: "tomato", code: "1F345" },
        { spanish: "zanahoria", english: "carrot", code: "1F955" },
        { spanish: "maíz", english: "corn", code: "1F33D" },
        { spanish: "pimiento", english: "pepper", code: "1FAD1" },
        { spanish: "pepino", english: "cucumber", code: "1F952" },
        { spanish: "brócoli", english: "broccoli", code: "1F966" },
        { spanish: "ajo", english: "garlic", code: "1F9C4" },
        { spanish: "cebolla", english: "onion", code: "1F9C5" },
        { spanish: "papa", english: "potato", code: "1F954" },
        { spanish: "batata", english: "sweet potato", code: "1F360" },
        { spanish: "lechuga", english: "lettuce", code: "1F96C" },
        { spanish: "champiñón", english: "mushroom", code: "1F344" },
        { spanish: "cacahuate", english: "peanut", code: "1F95C" },
        { spanish: "castaña", english: "chestnut", code: "1F330" },
        { spanish: "jengibre", english: "ginger", code: "1FADA" },

        // Prepared food
        { spanish: "pan", english: "bread", code: "1F35E" },
        { spanish: "croissant", english: "croissant", code: "1F950" },
        { spanish: "pretzel", english: "pretzel", code: "1F968" },
        { spanish: "bagel", english: "bagel", code: "1F96F" },
        { spanish: "tortilla", english: "flatbread", code: "1FAD3" },
        { spanish: "queso", english: "cheese", code: "1F9C0" },
        { spanish: "huevo", english: "egg", code: "1F95A" },
        { spanish: "tocino", english: "bacon", code: "1F953" },
        { spanish: "hamburguesa", english: "hamburger", code: "1F354" },
        { spanish: "pizza", english: "pizza", code: "1F355" },
        { spanish: "hotdog", english: "hot dog", code: "1F32D" },
        { spanish: "sándwich", english: "sandwich", code: "1F96A" },
        { spanish: "taco", english: "taco", code: "1F32E" },
        { spanish: "burrito", english: "burrito", code: "1F32F" },
        { spanish: "ensalada", english: "salad", code: "1F957" },
        { spanish: "sopa", english: "soup", code: "1F372" },
        { spanish: "espagueti", english: "spaghetti", code: "1F35D" },
        { spanish: "arroz", english: "rice", code: "1F35A" },
        { spanish: "curry", english: "curry", code: "1F35B" },
        { spanish: "sushi", english: "sushi", code: "1F363" },
        { spanish: "camarón frito", english: "fried shrimp", code: "1F364" },
        { spanish: "pollo", english: "chicken leg", code: "1F357" },
        { spanish: "carne", english: "meat", code: "1F356" },
        { spanish: "bistec", english: "steak", code: "1F969" },
        { spanish: "costilla", english: "ribs", code: "1F356" },

        // Sweets & desserts
        { spanish: "pastel", english: "cake", code: "1F370" },
        { spanish: "galleta", english: "cookie", code: "1F36A" },
        { spanish: "dona", english: "donut", code: "1F369" },
        { spanish: "helado", english: "ice cream", code: "1F368" },
        { spanish: "paleta", english: "popsicle", code: "1F366" },
        { spanish: "chocolate", english: "chocolate", code: "1F36B" },
        { spanish: "caramelo", english: "candy", code: "1F36C" },
        { spanish: "piruleta", english: "lollipop", code: "1F36D" },
        { spanish: "flan", english: "custard", code: "1F36E" },
        { spanish: "miel", english: "honey", code: "1F36F" },
        { spanish: "pie", english: "pie", code: "1F967" },
        { spanish: "cupcake", english: "cupcake", code: "1F9C1" },
        { spanish: "waffle", english: "waffle", code: "1F9C7" },
        { spanish: "panqueque", english: "pancake", code: "1F95E" },

        // Drinks
        { spanish: "café", english: "coffee", code: "2615" },
        { spanish: "té", english: "tea", code: "1F375" },
        { spanish: "leche", english: "milk", code: "1F95B" },
        { spanish: "jugo", english: "juice", code: "1F9C3" },
        { spanish: "agua", english: "water", code: "1F4A7" },
        { spanish: "refresco", english: "soda", code: "1F964" },
        { spanish: "cerveza", english: "beer", code: "1F37A" },
        { spanish: "vino", english: "wine", code: "1F377" },
        { spanish: "cóctel", english: "cocktail", code: "1F378" },
        { spanish: "champán", english: "champagne", code: "1F37E" },
        { spanish: "whisky", english: "whisky", code: "1F943" },
        { spanish: "mate", english: "mate", code: "1F9C9" },
        { spanish: "batido", english: "smoothie", code: "1F964" },
        { spanish: "hielo", english: "ice", code: "1F9CA" },
    ],

    // ===== NATURE =====
    nature: [
        // Weather & sky
        { spanish: "sol", english: "sun", code: "2600" },
        { spanish: "luna", english: "moon", code: "1F319" },
        { spanish: "estrella", english: "star", code: "2B50" },
        { spanish: "nube", english: "cloud", code: "2601" },
        { spanish: "lluvia", english: "rain", code: "1F327" },
        { spanish: "nieve", english: "snow", code: "1F328" },
        { spanish: "tormenta", english: "storm", code: "26C8" },
        { spanish: "rayo", english: "lightning", code: "26A1" },
        { spanish: "arcoíris", english: "rainbow", code: "1F308" },
        { spanish: "tornado", english: "tornado", code: "1F32A" },
        { spanish: "niebla", english: "fog", code: "1F32B" },
        { spanish: "viento", english: "wind", code: "1F32C" },
        { spanish: "cometa", english: "comet", code: "2604" },

        // Plants
        { spanish: "árbol", english: "tree", code: "1F333" },
        { spanish: "palmera", english: "palm tree", code: "1F334" },
        { spanish: "cactus", english: "cactus", code: "1F335" },
        { spanish: "flor", english: "flower", code: "1F33B" },
        { spanish: "rosa", english: "rose", code: "1F339" },
        { spanish: "tulipán", english: "tulip", code: "1F337" },
        { spanish: "girasol", english: "sunflower", code: "1F33B" },
        { spanish: "hoja", english: "leaf", code: "1F343" },
        { spanish: "trébol", english: "clover", code: "1F340" },
        { spanish: "hierba", english: "grass", code: "1F33F" },
        { spanish: "bambú", english: "bamboo", code: "1F38D" },
        { spanish: "helecho", english: "fern", code: "1F33F" },
        { spanish: "semilla", english: "seed", code: "1F331" },
        { spanish: "loto", english: "lotus", code: "1FAB7" },

        // Landscape
        { spanish: "montaña", english: "mountain", code: "26F0" },
        { spanish: "volcán", english: "volcano", code: "1F30B" },
        { spanish: "desierto", english: "desert", code: "1F3DC" },
        { spanish: "isla", english: "island", code: "1F3DD" },
        { spanish: "playa", english: "beach", code: "1F3D6" },
        { spanish: "océano", english: "ocean", code: "1F30A" },
        { spanish: "río", english: "river", code: "1F3DE" },
        { spanish: "bosque", english: "forest", code: "1F332" },
        { spanish: "cascada", english: "waterfall", code: "1F4A6" },

        // Elements
        { spanish: "fuego", english: "fire", code: "1F525" },
        { spanish: "agua", english: "water", code: "1F4A7" },
        { spanish: "tierra", english: "earth", code: "1F30D" },
        { spanish: "piedra", english: "rock", code: "1FAA8" },
        { spanish: "cristal", english: "crystal", code: "1F48E" },
    ],

    // ===== OBJECTS =====
    objects: [
        // Home
        { spanish: "casa", english: "house", code: "1F3E0" },
        { spanish: "edificio", english: "building", code: "1F3E2" },
        { spanish: "puerta", english: "door", code: "1F6AA" },
        { spanish: "ventana", english: "window", code: "1FA9F" },
        { spanish: "cama", english: "bed", code: "1F6CF" },
        { spanish: "sofá", english: "couch", code: "1F6CB" },
        { spanish: "silla", english: "chair", code: "1FA91" },
        { spanish: "mesa", english: "table", code: "1F4CF" },
        { spanish: "lámpara", english: "lamp", code: "1F4A1" },
        { spanish: "espejo", english: "mirror", code: "1FA9E" },
        { spanish: "reloj", english: "clock", code: "1F570" },
        { spanish: "llave", english: "key", code: "1F511" },
        { spanish: "cerradura", english: "lock", code: "1F512" },
        { spanish: "escalera", english: "ladder", code: "1FA9C" },
        { spanish: "cubo", english: "bucket", code: "1FAA3" },
        { spanish: "escoba", english: "broom", code: "1F9F9" },

        // Technology
        { spanish: "teléfono", english: "phone", code: "1F4F1" },
        { spanish: "computadora", english: "computer", code: "1F4BB" },
        { spanish: "televisión", english: "television", code: "1F4FA" },
        { spanish: "cámara", english: "camera", code: "1F4F7" },
        { spanish: "radio", english: "radio", code: "1F4FB" },
        { spanish: "batería", english: "battery", code: "1F50B" },
        { spanish: "enchufe", english: "plug", code: "1F50C" },
        { spanish: "linterna", english: "flashlight", code: "1F526" },
        { spanish: "imán", english: "magnet", code: "1F9F2" },
        { spanish: "robot", english: "robot", code: "1F916" },

        // Transportation
        { spanish: "coche", english: "car", code: "1F697" },
        { spanish: "autobús", english: "bus", code: "1F68C" },
        { spanish: "camión", english: "truck", code: "1F69A" },
        { spanish: "motocicleta", english: "motorcycle", code: "1F3CD" },
        { spanish: "bicicleta", english: "bicycle", code: "1F6B2" },
        { spanish: "tren", english: "train", code: "1F686" },
        { spanish: "avión", english: "airplane", code: "2708" },
        { spanish: "helicóptero", english: "helicopter", code: "1F681" },
        { spanish: "barco", english: "ship", code: "1F6A2" },
        { spanish: "cohete", english: "rocket", code: "1F680" },
        { spanish: "taxi", english: "taxi", code: "1F695" },
        { spanish: "ambulancia", english: "ambulance", code: "1F691" },
        { spanish: "tractor", english: "tractor", code: "1F69C" },
        { spanish: "patineta", english: "skateboard", code: "1F6F9" },
        { spanish: "canoa", english: "canoe", code: "1F6F6" },

        // Tools
        { spanish: "martillo", english: "hammer", code: "1F528" },
        { spanish: "destornillador", english: "screwdriver", code: "1FA9B" },
        { spanish: "llave inglesa", english: "wrench", code: "1F527" },
        { spanish: "sierra", english: "saw", code: "1FA9A" },
        { spanish: "tijeras", english: "scissors", code: "2702" },
        { spanish: "cuchillo", english: "knife", code: "1F52A" },
        { spanish: "hacha", english: "axe", code: "1FA93" },
        { spanish: "gancho", english: "hook", code: "1FA9D" },

        // School & office
        { spanish: "libro", english: "book", code: "1F4D6" },
        { spanish: "cuaderno", english: "notebook", code: "1F4D3" },
        { spanish: "lápiz", english: "pencil", code: "270F" },
        { spanish: "bolígrafo", english: "pen", code: "1F58A" },
        { spanish: "regla", english: "ruler", code: "1F4CF" },
        { spanish: "mochila", english: "backpack", code: "1F392" },
        { spanish: "globo terráqueo", english: "globe", code: "1F30D" },
        { spanish: "calculadora", english: "calculator", code: "1F5A9" },
        { spanish: "clip", english: "paperclip", code: "1F4CE" },
        { spanish: "sobre", english: "envelope", code: "2709" },
        { spanish: "calendario", english: "calendar", code: "1F4C5" },

        // Clothing
        { spanish: "camisa", english: "shirt", code: "1F455" },
        { spanish: "pantalones", english: "pants", code: "1F456" },
        { spanish: "vestido", english: "dress", code: "1F457" },
        { spanish: "falda", english: "skirt", code: "1FA73" },
        { spanish: "abrigo", english: "coat", code: "1F9E5" },
        { spanish: "suéter", english: "sweater", code: "1F9E6" },
        { spanish: "calcetines", english: "socks", code: "1F9E6" },
        { spanish: "zapatos", english: "shoes", code: "1F45E" },
        { spanish: "botas", english: "boots", code: "1F97E" },
        { spanish: "sandalias", english: "sandals", code: "1FA74" },
        { spanish: "sombrero", english: "hat", code: "1F3A9" },
        { spanish: "gorra", english: "cap", code: "1F9E2" },
        { spanish: "bufanda", english: "scarf", code: "1F9E3" },
        { spanish: "guantes", english: "gloves", code: "1F9E4" },
        { spanish: "corbata", english: "tie", code: "1F454" },
        { spanish: "cinturón", english: "belt", code: "1F4FF" },
        { spanish: "gafas", english: "glasses", code: "1F453" },
        { spanish: "reloj de pulsera", english: "watch", code: "231A" },
        { spanish: "anillo", english: "ring", code: "1F48D" },
        { spanish: "collar", english: "necklace", code: "1F4FF" },
        { spanish: "bolso", english: "purse", code: "1F45C" },
        { spanish: "maleta", english: "suitcase", code: "1F9F3" },
        { spanish: "paraguas", english: "umbrella", code: "2602" },
    ],

    // ===== PLACES =====
    places: [
        { spanish: "hospital", english: "hospital", code: "1F3E5" },
        { spanish: "escuela", english: "school", code: "1F3EB" },
        { spanish: "banco", english: "bank", code: "1F3E6" },
        { spanish: "hotel", english: "hotel", code: "1F3E8" },
        { spanish: "tienda", english: "store", code: "1F3EA" },
        { spanish: "restaurante", english: "restaurant", code: "1F37D" },
        { spanish: "iglesia", english: "church", code: "26EA" },
        { spanish: "castillo", english: "castle", code: "1F3F0" },
        { spanish: "estadio", english: "stadium", code: "1F3DF" },
        { spanish: "fábrica", english: "factory", code: "1F3ED" },
        { spanish: "biblioteca", english: "library", code: "1F4DA" },
        { spanish: "parque", english: "park", code: "1F3DE" },
        { spanish: "circo", english: "circus", code: "1F3AA" },
        { spanish: "cine", english: "cinema", code: "1F3AC" },
    ],

    // ===== SPORTS & ACTIVITIES =====
    sports: [
        { spanish: "fútbol", english: "soccer ball", code: "26BD" },
        { spanish: "baloncesto", english: "basketball", code: "1F3C0" },
        { spanish: "béisbol", english: "baseball", code: "26BE" },
        { spanish: "tenis", english: "tennis", code: "1F3BE" },
        { spanish: "voleibol", english: "volleyball", code: "1F3D0" },
        { spanish: "rugby", english: "rugby", code: "1F3C9" },
        { spanish: "golf", english: "golf", code: "26F3" },
        { spanish: "billar", english: "pool", code: "1F3B1" },
        { spanish: "boliche", english: "bowling", code: "1F3B3" },
        { spanish: "boxeo", english: "boxing", code: "1F94A" },
        { spanish: "arco", english: "bow and arrow", code: "1F3F9" },
        { spanish: "esquí", english: "ski", code: "1F3BF" },
        { spanish: "patines", english: "ice skate", code: "26F8" },
        { spanish: "surf", english: "surfing", code: "1F3C4" },
        { spanish: "pesca", english: "fishing", code: "1F3A3" },
        { spanish: "ajedrez", english: "chess", code: "265F" },
        { spanish: "dados", english: "dice", code: "1F3B2" },
        { spanish: "naipes", english: "cards", code: "1F0CF" },
    ],

    // ===== BODY PARTS =====
    body: [
        { spanish: "ojo", english: "eye", code: "1F441" },
        { spanish: "oreja", english: "ear", code: "1F442" },
        { spanish: "nariz", english: "nose", code: "1F443" },
        { spanish: "boca", english: "mouth", code: "1F444" },
        { spanish: "lengua", english: "tongue", code: "1F445" },
        { spanish: "mano", english: "hand", code: "270B" },
        { spanish: "pie", english: "foot", code: "1F9B6" },
        { spanish: "pierna", english: "leg", code: "1F9B5" },
        { spanish: "brazo", english: "arm", code: "1F4AA" },
        { spanish: "dedo", english: "finger", code: "1F446" },
        { spanish: "corazón", english: "heart", code: "2764" },
        { spanish: "cerebro", english: "brain", code: "1F9E0" },
        { spanish: "hueso", english: "bone", code: "1F9B4" },
        { spanish: "diente", english: "tooth", code: "1F9B7" },
    ],

    // ===== EMOTIONS =====
    emotions: [
        { spanish: "feliz", english: "happy", code: "1F600" },
        { spanish: "triste", english: "sad", code: "1F622" },
        { spanish: "enojado", english: "angry", code: "1F621" },
        { spanish: "asustado", english: "scared", code: "1F628" },
        { spanish: "sorprendido", english: "surprised", code: "1F62E" },
        { spanish: "confundido", english: "confused", code: "1F615" },
        { spanish: "cansado", english: "tired", code: "1F634" },
        { spanish: "enfermo", english: "sick", code: "1F912" },
        { spanish: "enamorado", english: "in love", code: "1F60D" },
        { spanish: "orgulloso", english: "proud", code: "1F60E" },
        { spanish: "nervioso", english: "nervous", code: "1F630" },
        { spanish: "aburrido", english: "bored", code: "1F971" },
    ],

    // ===== MUSIC & ARTS =====
    music: [
        { spanish: "guitarra", english: "guitar", code: "1F3B8" },
        { spanish: "piano", english: "piano", code: "1F3B9" },
        { spanish: "violín", english: "violin", code: "1F3BB" },
        { spanish: "trompeta", english: "trumpet", code: "1F3BA" },
        { spanish: "tambor", english: "drum", code: "1F941" },
        { spanish: "saxofón", english: "saxophone", code: "1F3B7" },
        { spanish: "micrófono", english: "microphone", code: "1F3A4" },
        { spanish: "auriculares", english: "headphones", code: "1F3A7" },
        { spanish: "paleta", english: "palette", code: "1F3A8" },
        { spanish: "pincel", english: "paintbrush", code: "1F58C" },
        { spanish: "teatro", english: "theater", code: "1F3AD" },
        { spanish: "película", english: "movie", code: "1F3AC" },
    ],
};

// Helper function to get all vocab as flat array
function getAllVocab() {
    return Object.values(spanishVocab).flat();
}

// Helper function to get vocab by category
function getVocabByCategory(category) {
    return spanishVocab[category] || [];
}

// Helper function to get OpenMoji path
function getEmojiPath(code) {
    return `images/openmoji/${code}.svg`;
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { spanishVocab, getAllVocab, getVocabByCategory, getEmojiPath };
}
